svc_param_index:
  path: /
  controller: Svc\ParamBundle\Controller\ParamsController::index

svc_param_edit:
  path: /{id}
  controller: Svc\ParamBundle\Controller\ParamsController::edit

svc_param_delete:
  path: /delete/{id}
  controller: Svc\ParamBundle\Controller\ParamsController::delete
