services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Svc\ParamBundle\Controller\ParamsController:
  Svc\ParamBundle\Repository\ParamsRepository:
  Svc\ParamBundle\Controller\EaParamsCrudController:
